# Jekyll Configuration

# Site Settings
url: "https://littleavel.github.io/"
website_url: "https://littleavel.github.io/"
title: "CSS"
email: little.avel@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog